output1.cu.o: /home/joshp/JetPack_Android_3.1/cuda-8.0/bin/crt/link.stub \
 /home/joshp/JetPack_Android_3.1/cuda-8.0/bin/../targets/armv7-linux-androideabi/include/host_defines.h \
 /home/joshp/JetPack_Android_3.1/cuda-8.0/bin/../targets/armv7-linux-androideabi/include/fatBinaryCtl.h \
 /home/joshp/JetPack_Android_3.1/cuda-8.0/bin/../targets/armv7-linux-androideabi/include/fatbinary.h \
 /tmp/tmpxft_0002115c_00000000-7_output3_dlink.reg.c \
 /tmp/tmpxft_0002115c_00000000-8_output3_dlink.fatbin.c

/home/joshp/JetPack_Android_3.1/cuda-8.0/bin/../targets/armv7-linux-androideabi/include/host_defines.h:

/home/joshp/JetPack_Android_3.1/cuda-8.0/bin/../targets/armv7-linux-androideabi/include/fatBinaryCtl.h:

/home/joshp/JetPack_Android_3.1/cuda-8.0/bin/../targets/armv7-linux-androideabi/include/fatbinary.h:

/tmp/tmpxft_0002115c_00000000-7_output3_dlink.reg.c:

/tmp/tmpxft_0002115c_00000000-8_output3_dlink.fatbin.c:
